<?php
/**
 * Plugin Name: Woo JSON Metadata Importer
 * Plugin URI: https://example.com
 * Description: Imports a metadata.json file (generated by the scraper) into WooCommerce.
 * Version: 1.0.1
 * Author: Local
 * License: GPL-2.0-or-later
 */

if (!defined('ABSPATH')) {
	exit;
}

	if (!class_exists('WJMI_Plugin')) {
		class WJMI_Plugin {
			const MENU_SLUG = 'wjmi-import-json';
			const NONCE_ACTION = 'wjmi_import_json';
			const JOB_TRANSIENT_TTL = 21600; // 6 hours
			const DEFAULT_CHUNK_SIZE = 5;

		public function __construct() {
			add_action('admin_menu', array($this, 'register_admin_page'));
			add_action('admin_post_wjmi_import_json', array($this, 'handle_import'));
			add_action('wp_ajax_wjmi_start_import', array($this, 'ajax_start_import'));
			add_action('wp_ajax_wjmi_process_import', array($this, 'ajax_process_import'));
		}

		public function register_admin_page() {
			add_submenu_page(
				'woocommerce',
				'Import JSON Metadata',
				'Import JSON Metadata',
				$this->required_capability(),
				self::MENU_SLUG,
				array($this, 'render_admin_page')
			);
		}

		private function required_capability() {
			if (current_user_can('manage_woocommerce')) {
				return 'manage_woocommerce';
			}

			return 'manage_options';
		}

		public function render_admin_page() {
			if (!current_user_can($this->required_capability())) {
				wp_die(esc_html__('You do not have permission to access this page.', 'woo-json-metadata-importer'));
			}

			$status = isset($_GET['wjmi_status']) ? sanitize_key(wp_unslash($_GET['wjmi_status'])) : '';
			$message = isset($_GET['wjmi_message']) ? sanitize_text_field(wp_unslash($_GET['wjmi_message'])) : '';
			$details = isset($_GET['wjmi_details']) ? sanitize_text_field(wp_unslash($_GET['wjmi_details'])) : '';
			$ajax_nonce = wp_create_nonce(self::NONCE_ACTION);
			?>
			<div class="wrap">
				<h1 class="wp-heading-inline">Woo JSON Metadata Importer</h1>
				<hr class="wp-header-end" />

				<?php if (!class_exists('WooCommerce')) : ?>
					<div class="notice notice-error"><p><?php echo esc_html__('WooCommerce is not active.', 'woo-json-metadata-importer'); ?></p></div>
				<?php endif; ?>

				<?php if (!empty($message)) : ?>
					<?php
					$class = 'notice-error';
					if ('success' === $status) {
						$class = 'notice-success';
					} elseif ('warning' === $status) {
						$class = 'notice-warning';
					}
					?>
					<div class="notice <?php echo esc_attr($class); ?> is-dismissible">
						<p><strong><?php echo esc_html($message); ?></strong></p>
						<?php if (!empty($details)) : ?>
							<p><?php echo esc_html($details); ?></p>
						<?php endif; ?>
					</div>
				<?php endif; ?>

					<div class="notice notice-info inline">
						<p><?php echo wp_kses_post(__('Upload your <code>metadata.json</code> file to create or update WooCommerce products.', 'woo-json-metadata-importer')); ?></p>
					</div>
					<div id="wjmi-live-notice"></div>

				<div id="poststuff">
					<div id="post-body" class="metabox-holder columns-2">
						<div id="post-body-content">
							<div class="postbox">
								<div class="postbox-header">
									<h2 class="hndle"><?php echo esc_html__('Import file', 'woo-json-metadata-importer'); ?></h2>
								</div>
								<div class="inside">
									<form id="wjmi-import-form" method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>" enctype="multipart/form-data" data-nonce="<?php echo esc_attr($ajax_nonce); ?>">
										<input type="hidden" name="action" value="wjmi_import_json" />
										<?php wp_nonce_field(self::NONCE_ACTION); ?>
										<table class="form-table" role="presentation">
											<tbody>
												<tr>
													<th scope="row"><label for="metadata_file"><?php echo esc_html__('JSON file', 'woo-json-metadata-importer'); ?></label></th>
													<td>
														<input type="file" id="metadata_file" name="metadata_file" accept=".json,application/json" required />
														<p class="description"><?php echo wp_kses_post(__('Expected format: object with key <code>products</code> (array) or a direct array of products.', 'woo-json-metadata-importer')); ?></p>
													</td>
												</tr>
											</tbody>
										</table>
										<?php submit_button(__('Import JSON into WooCommerce', 'woo-json-metadata-importer'), 'primary', 'submit', false, array('id' => 'wjmi-submit-btn')); ?>
										<span class="spinner" id="wjmi-spinner" aria-hidden="true"></span>
									</form>
									<noscript>
										<p class="description"><?php echo esc_html__('JavaScript is required to show real-time progress. Without JavaScript, import runs in a single request.', 'woo-json-metadata-importer'); ?></p>
									</noscript>
								</div>
							</div>

								<div class="postbox" id="wjmi-progress-box" hidden>
									<div class="postbox-header">
										<h2 class="hndle"><?php echo esc_html__('Live import progress', 'woo-json-metadata-importer'); ?></h2>
									</div>
									<div class="inside">
									<p><strong><?php echo esc_html__('Current stage:', 'woo-json-metadata-importer'); ?></strong> <span id="wjmi-stage-text"><?php echo esc_html__('Waiting to start...', 'woo-json-metadata-importer'); ?></span></p>
									<progress id="wjmi-progress-bar" value="0" max="100"></progress>
									<p id="wjmi-progress-label"><?php echo esc_html__('0% completed', 'woo-json-metadata-importer'); ?></p>
									<table class="widefat striped" id="wjmi-progress-metrics">
										<tbody>
											<tr>
												<td><strong><?php echo esc_html__('Total products', 'woo-json-metadata-importer'); ?></strong><br /><span id="wjmi-total">0</span></td>
												<td><strong><?php echo esc_html__('Processed', 'woo-json-metadata-importer'); ?></strong><br /><span id="wjmi-processed">0</span></td>
												<td><strong><?php echo esc_html__('Remaining', 'woo-json-metadata-importer'); ?></strong><br /><span id="wjmi-remaining">0</span></td>
												<td><strong><?php echo esc_html__('Created', 'woo-json-metadata-importer'); ?></strong><br /><span id="wjmi-created">0</span></td>
												<td><strong><?php echo esc_html__('Updated', 'woo-json-metadata-importer'); ?></strong><br /><span id="wjmi-updated">0</span></td>
												<td><strong><?php echo esc_html__('Failed', 'woo-json-metadata-importer'); ?></strong><br /><span id="wjmi-failed">0</span></td>
											</tr>
										</tbody>
									</table>
										<div class="notice notice-warning inline" id="wjmi-errors-box" hidden>
											<p><strong><?php echo esc_html__('Recent errors', 'woo-json-metadata-importer'); ?></strong></p>
											<ul id="wjmi-errors-list"></ul>
										</div>
										<div class="notice notice-info inline" id="wjmi-activity-box" hidden>
											<p><strong><?php echo esc_html__('Current activity', 'woo-json-metadata-importer'); ?></strong></p>
											<ul id="wjmi-activity-list"></ul>
										</div>
									</div>
								</div>
						</div>

						<div id="postbox-container-1" class="postbox-container">
							<div class="postbox">
								<div class="postbox-header">
									<h2 class="hndle"><?php echo esc_html__('Quick checklist', 'woo-json-metadata-importer'); ?></h2>
								</div>
								<div class="inside">
									<ul>
										<li><?php echo esc_html__('WooCommerce is active.', 'woo-json-metadata-importer'); ?></li>
										<li><?php echo esc_html__('Use the latest metadata.json generated by the scraper.', 'woo-json-metadata-importer'); ?></li>
										<li><?php echo esc_html__('Re-importing updates products by SKU/source IDs.', 'woo-json-metadata-importer'); ?></li>
									</ul>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<style>
				#wjmi-progress-bar {
					width: 100%;
					height: 16px;
					margin: 0.2rem 0 0.4rem;
				}
				#wjmi-progress-label {
					margin-top: 0;
					color: #50575e;
				}
				#wjmi-progress-metrics td {
					width: 16.66%;
					vertical-align: top;
				}
					#wjmi-errors-list {
						margin: 0.2rem 0 0.2rem 1.1rem;
					}
					#wjmi-activity-list {
						margin: 0.2rem 0 0.2rem 1.1rem;
					}
					#wjmi-spinner {
						float: none;
						margin: 0 0 0 8px;
					}
					#wjmi-live-notice .notice {
						margin: 12px 0;
					}
				</style>
				<script>
					(function () {
						const form = document.getElementById('wjmi-import-form');
						if (!form) {
							return;
						}

						const nonce = form.dataset.nonce || '';
						const submitBtn = document.getElementById('wjmi-submit-btn');
						const spinner = document.getElementById('wjmi-spinner');
						const progressBox = document.getElementById('wjmi-progress-box');
						const stageText = document.getElementById('wjmi-stage-text');
						const progressBar = document.getElementById('wjmi-progress-bar');
						const progressLabel = document.getElementById('wjmi-progress-label');
						const totalEl = document.getElementById('wjmi-total');
						const processedEl = document.getElementById('wjmi-processed');
						const remainingEl = document.getElementById('wjmi-remaining');
						const createdEl = document.getElementById('wjmi-created');
						const updatedEl = document.getElementById('wjmi-updated');
						const failedEl = document.getElementById('wjmi-failed');
						const errorsBox = document.getElementById('wjmi-errors-box');
						const errorsList = document.getElementById('wjmi-errors-list');
						const activityBox = document.getElementById('wjmi-activity-box');
						const activityList = document.getElementById('wjmi-activity-list');
						const liveNotice = document.getElementById('wjmi-live-notice');
						let currentJobId = '';
						let running = false;

						function setRunningState(value) {
							running = Boolean(value);
							if (submitBtn) {
								submitBtn.disabled = running;
								submitBtn.textContent = running ? 'Importing...' : 'Import JSON into WooCommerce';
							}
							if (spinner) {
								spinner.classList.toggle('is-active', running);
							}
						}

						function renderList(listElement, items) {
							if (!listElement) {
								return;
							}

							listElement.innerHTML = '';
							if (!Array.isArray(items) || items.length === 0) {
								return;
							}

							items.forEach(function (item) {
								const li = document.createElement('li');
								li.textContent = String(item);
								listElement.appendChild(li);
							});
						}

						function clearErrors() {
							if (!errorsBox) {
								return;
							}
							renderList(errorsList, []);
							errorsBox.hidden = true;
						}

						function updateErrors(errors) {
							if (!errorsBox) {
								return;
							}

							if (!Array.isArray(errors) || errors.length === 0) {
								clearErrors();
								return;
							}

							renderList(errorsList, errors);
							errorsBox.hidden = false;
						}

						function updateActivity(activity) {
							if (!activityBox) {
								return;
							}
							renderList(activityList, activity);
							activityBox.hidden = !Array.isArray(activity) || activity.length === 0;
						}

						function showLiveNotice(type, message) {
							if (!liveNotice) {
								return;
							}

							liveNotice.innerHTML = '';
							if (!message) {
								return;
							}

							const box = document.createElement('div');
							box.className = 'notice is-dismissible';
							if (type === 'success') {
								box.classList.add('notice-success');
							} else if (type === 'warning') {
								box.classList.add('notice-warning');
							} else {
								box.classList.add('notice-error');
							}

							const p = document.createElement('p');
							p.textContent = String(message);
							box.appendChild(p);
							liveNotice.appendChild(box);
						}

						function renderState(state) {
							if (!state) {
								return;
							}

							progressBox.hidden = false;

							const total = Number(state.total || 0);
							const processed = Number(state.processed || 0);
							const remaining = Number(state.remaining || Math.max(0, total - processed));
							const created = Number(state.created || 0);
							const updated = Number(state.updated || 0);
							const failed = Number(state.failed || 0);
							const percent = total > 0 ? Math.min(100, Math.round((processed / total) * 100)) : 0;

							stageText.textContent = state.stage || 'Running import...';
							progressBar.value = percent;
							progressLabel.textContent = percent + '% completed';
							totalEl.textContent = String(total);
							processedEl.textContent = String(processed);
							remainingEl.textContent = String(remaining);
							createdEl.textContent = String(created);
							updatedEl.textContent = String(updated);
							failedEl.textContent = String(failed);
							updateErrors(state.errors || []);
							updateActivity(state.activity || []);
						}

						async function postJsonLike(payload, useFormData) {
							const fetchOptions = {
								method: 'POST',
								credentials: 'same-origin'
							};

							if (useFormData) {
								fetchOptions.body = payload;
							} else {
								fetchOptions.headers = {
									'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8'
								};
								fetchOptions.body = new URLSearchParams(payload).toString();
							}

							const response = await fetch(ajaxurl, fetchOptions);
							const text = await response.text();
							let data = null;

							try {
								data = JSON.parse(text);
							} catch (error) {
								throw new Error('Unexpected server response. Check the PHP error log for details.');
							}

							if (!response.ok) {
								throw new Error((data && data.data && data.data.message) || 'Request failed.');
							}

							return data;
						}

						async function processNextChunk() {
							if (!running || !currentJobId) {
								return;
							}

							try {
								const payload = await postJsonLike(
									{
										action: 'wjmi_process_import',
										nonce: nonce,
										job_id: currentJobId
									},
									false
								);

								if (!payload || payload.success !== true || !payload.data || !payload.data.state) {
									throw new Error((payload && payload.data && payload.data.message) || 'Unable to process import chunk.');
								}

								const state = payload.data.state;
								renderState(state);

								if (state.status === 'running') {
									setTimeout(processNextChunk, 150);
									return;
								}

								setRunningState(false);
								if (state.status === 'completed') {
									showLiveNotice('success', state.stage || 'Import completed.');
								} else if (state.status === 'warning') {
									showLiveNotice('warning', state.stage || 'Import completed with warnings.');
								} else if (state.status === 'failed') {
									showLiveNotice('error', state.stage || 'Import failed.');
								}
							} catch (error) {
								setRunningState(false);
								stageText.textContent = 'Import failed: ' + error.message;
								showLiveNotice('error', 'Import failed: ' + error.message);
							}
						}

						form.addEventListener('submit', async function (event) {
							event.preventDefault();

							const fileInput = document.getElementById('metadata_file');
							if (!fileInput || !fileInput.files || fileInput.files.length === 0) {
								window.alert('Please choose a JSON file before importing.');
								return;
							}

							showLiveNotice('', '');
							clearErrors();
							updateActivity([]);
							progressBox.hidden = false;
							stageText.textContent = 'Preparing import job...';
							progressBar.value = 0;
							progressLabel.textContent = '0% completed';
							totalEl.textContent = '0';
							processedEl.textContent = '0';
							remainingEl.textContent = '0';
							createdEl.textContent = '0';
							updatedEl.textContent = '0';
							failedEl.textContent = '0';
							setRunningState(true);

							try {
								const formData = new FormData();
								formData.append('action', 'wjmi_start_import');
								formData.append('nonce', nonce);
								formData.append('metadata_file', fileInput.files[0]);

								const payload = await postJsonLike(formData, true);
								if (!payload || payload.success !== true || !payload.data || !payload.data.job_id) {
									throw new Error((payload && payload.data && payload.data.message) || 'Unable to start import.');
								}

								currentJobId = payload.data.job_id;
								renderState(payload.data.state || {});
								setTimeout(processNextChunk, 150);
							} catch (error) {
								setRunningState(false);
								stageText.textContent = 'Import failed: ' + error.message;
								showLiveNotice('error', 'Import failed: ' + error.message);
							}
						});
					})();
				</script>
				<?php
			}

			public function ajax_start_import() {
				if (!current_user_can($this->required_capability())) {
					wp_send_json_error(array('message' => 'You do not have permission to perform this action.'), 403);
				}

				$nonce = isset($_POST['nonce']) ? sanitize_text_field(wp_unslash($_POST['nonce'])) : '';
				if (!wp_verify_nonce($nonce, self::NONCE_ACTION)) {
					wp_send_json_error(array('message' => 'Security check failed. Please reload this page.'), 403);
				}

				if (!class_exists('WooCommerce')) {
					wp_send_json_error(array('message' => 'WooCommerce is not active.'), 400);
				}

				if (
					empty($_FILES['metadata_file']) ||
					!is_array($_FILES['metadata_file']) ||
					empty($_FILES['metadata_file']['tmp_name'])
				) {
					wp_send_json_error(array('message' => 'No file was uploaded.'), 400);
				}

				$file = $_FILES['metadata_file'];
				if (!empty($file['error'])) {
					wp_send_json_error(array('message' => 'JSON file upload failed.'), 400);
				}

				$rawJson = file_get_contents($file['tmp_name']); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_get_contents_file_get_contents
				if (false === $rawJson || '' === trim($rawJson)) {
					wp_send_json_error(array('message' => 'Unable to read the uploaded file.'), 400);
				}

				$payload = json_decode($rawJson, true);
				if (JSON_ERROR_NONE !== json_last_error()) {
					wp_send_json_error(array('message' => 'Invalid JSON: ' . json_last_error_msg()), 400);
				}

				try {
					$products = $this->extract_products($payload);
				} catch (Exception $exception) {
					wp_send_json_error(array('message' => $exception->getMessage()), 400);
				}

				$products = $this->compact_products_for_job($products);
				$total = count($products);
				if ($total < 1) {
					wp_send_json_error(array('message' => 'No products were found in the JSON payload.'), 400);
				}

				$jobId = $this->generate_job_id();
				$state = array(
					'status' => 'running',
					'stage' => sprintf('Import queued. %d product%s ready.', $total, 1 === $total ? '' : 's'),
					'total' => $total,
					'processed' => 0,
					'remaining' => $total,
					'created' => 0,
					'updated' => 0,
					'failed' => 0,
					'errors' => array(),
					'activity' => array(sprintf('Job created with %d product%s.', $total, 1 === $total ? '' : 's')),
					'products' => $products,
					'started_at' => time(),
					'updated_at' => time(),
				);

				$this->save_job_state($jobId, $state);

				wp_send_json_success(
					array(
						'job_id' => $jobId,
						'state' => $this->public_job_state($state),
					)
				);
			}

			public function ajax_process_import() {
				if (!current_user_can($this->required_capability())) {
					wp_send_json_error(array('message' => 'You do not have permission to perform this action.'), 403);
				}

				$nonce = isset($_POST['nonce']) ? sanitize_text_field(wp_unslash($_POST['nonce'])) : '';
				if (!wp_verify_nonce($nonce, self::NONCE_ACTION)) {
					wp_send_json_error(array('message' => 'Security check failed. Please reload this page.'), 403);
				}

				$jobId = isset($_POST['job_id']) ? sanitize_key(wp_unslash($_POST['job_id'])) : '';
				if ('' === $jobId) {
					wp_send_json_error(array('message' => 'Missing import job id.'), 400);
				}

				$state = $this->get_job_state($jobId);
				if (!is_array($state)) {
					wp_send_json_error(array('message' => 'Import job not found or expired. Please start again.'), 404);
				}

				$status = isset($state['status']) ? (string) $state['status'] : 'running';
				if (in_array($status, array('completed', 'warning', 'failed'), true)) {
					wp_send_json_success(array('state' => $this->public_job_state($state)));
				}

				if (empty($state['products']) || !is_array($state['products'])) {
					$state['status'] = 'failed';
					$state['stage'] = 'Import data is unavailable. Please start again.';
					$state['updated_at'] = time();
					$this->save_job_state($jobId, $state);
					wp_send_json_success(array('state' => $this->public_job_state($state)));
				}

				$total = isset($state['total']) ? (int) $state['total'] : count($state['products']);
				$total = max(0, $total);
				$processed = isset($state['processed']) ? (int) $state['processed'] : 0;
				$processed = max(0, min($total, $processed));

				if ($processed >= $total) {
					$state['status'] = $state['failed'] > 0 ? 'warning' : 'completed';
					$state['stage'] = sprintf(
						'Import completed. Created: %d | Updated: %d | Failed: %d',
						(int) $state['created'],
						(int) $state['updated'],
						(int) $state['failed']
					);
					$state['products'] = array();
					$state['updated_at'] = time();
					$this->save_job_state($jobId, $state);
					wp_send_json_success(array('state' => $this->public_job_state($state)));
				}

				$chunkSize = (int) apply_filters('wjmi_import_chunk_size', self::DEFAULT_CHUNK_SIZE);
				if ($chunkSize < 1) {
					$chunkSize = self::DEFAULT_CHUNK_SIZE;
				}

				$startIndex = $processed;
				$endIndex = min($total, $startIndex + $chunkSize);
				$state['stage'] = sprintf('Processing products %1$d-%2$d of %3$d...', $startIndex + 1, $endIndex, $total);
				$state['updated_at'] = time();

				for ($index = $startIndex; $index < $endIndex; $index++) {
					$productData = isset($state['products'][$index]) ? $state['products'][$index] : null;
					$productName = sprintf('Product #%d', $index + 1);

					if (is_array($productData) && !empty($productData['name'])) {
						$productName = sanitize_text_field((string) $productData['name']);
					}

					try {
						$result = $this->import_product($productData);
						if ('created' === $result) {
							$state['created'] = (int) $state['created'] + 1;
							$this->push_job_activity($state, sprintf('[%1$d/%2$d] Created: %3$s', $index + 1, $total, $productName));
						} else {
							$state['updated'] = (int) $state['updated'] + 1;
							$this->push_job_activity($state, sprintf('[%1$d/%2$d] Updated: %3$s', $index + 1, $total, $productName));
						}
					} catch (Throwable $exception) {
						$state['failed'] = (int) $state['failed'] + 1;
						$errorMessage = sprintf('Product #%1$d (%2$s): %3$s', $index + 1, $productName, $exception->getMessage());
						$this->push_job_error($state, $errorMessage);
						$this->push_job_activity($state, sprintf('[%1$d/%2$d] Failed: %3$s', $index + 1, $total, $productName));
					}

					$state['processed'] = $index + 1;
					$state['remaining'] = max(0, $total - (int) $state['processed']);
					$state['products'][$index] = null;
				}

				if ((int) $state['processed'] >= $total) {
					$state['status'] = (int) $state['failed'] > 0 ? 'warning' : 'completed';
					$state['stage'] = sprintf(
						'Import completed. Created: %d | Updated: %d | Failed: %d',
						(int) $state['created'],
						(int) $state['updated'],
						(int) $state['failed']
					);
					$state['products'] = array();
				} else {
					$state['status'] = 'running';
					$state['stage'] = sprintf(
						'Processed %1$d of %2$d. Remaining: %3$d.',
						(int) $state['processed'],
						$total,
						(int) $state['remaining']
					);
				}

				$state['updated_at'] = time();
				$this->save_job_state($jobId, $state);
				wp_send_json_success(array('state' => $this->public_job_state($state)));
			}

			private function generate_job_id() {
				return strtolower(wp_generate_password(20, false, false));
			}

			private function job_transient_key($jobId) {
				return 'wjmi_job_' . sanitize_key((string) $jobId);
			}

			private function save_job_state($jobId, $state) {
				set_transient($this->job_transient_key($jobId), $state, self::JOB_TRANSIENT_TTL);
			}

			private function get_job_state($jobId) {
				$state = get_transient($this->job_transient_key($jobId));
				return is_array($state) ? $state : null;
			}

			private function public_job_state($state) {
				$total = isset($state['total']) ? (int) $state['total'] : 0;
				$total = max(0, $total);
				$processed = isset($state['processed']) ? (int) $state['processed'] : 0;
				$processed = max(0, min($total, $processed));
				$remaining = isset($state['remaining']) ? (int) $state['remaining'] : max(0, $total - $processed);
				$remaining = max(0, $remaining);

				$status = isset($state['status']) ? sanitize_key((string) $state['status']) : 'running';
				if (!in_array($status, array('running', 'completed', 'warning', 'failed'), true)) {
					$status = 'running';
				}

				$errors = array();
				if (!empty($state['errors']) && is_array($state['errors'])) {
					$errors = array_slice(array_map('sanitize_text_field', $state['errors']), -10);
				}

				$activity = array();
				if (!empty($state['activity']) && is_array($state['activity'])) {
					$activity = array_slice(array_map('sanitize_text_field', $state['activity']), -12);
				}

				return array(
					'status' => $status,
					'stage' => isset($state['stage']) ? sanitize_text_field((string) $state['stage']) : 'Running import...',
					'total' => $total,
					'processed' => $processed,
					'remaining' => $remaining,
					'created' => isset($state['created']) ? (int) $state['created'] : 0,
					'updated' => isset($state['updated']) ? (int) $state['updated'] : 0,
					'failed' => isset($state['failed']) ? (int) $state['failed'] : 0,
					'errors' => array_values($errors),
					'activity' => array_values($activity),
					'started_at' => isset($state['started_at']) ? (int) $state['started_at'] : 0,
					'updated_at' => isset($state['updated_at']) ? (int) $state['updated_at'] : 0,
				);
			}

			private function push_job_error(&$state, $message) {
				if (!isset($state['errors']) || !is_array($state['errors'])) {
					$state['errors'] = array();
				}

				$state['errors'][] = sanitize_text_field((string) $message);
				if (count($state['errors']) > 10) {
					$state['errors'] = array_slice($state['errors'], -10);
				}
			}

			private function push_job_activity(&$state, $message) {
				if (!isset($state['activity']) || !is_array($state['activity'])) {
					$state['activity'] = array();
				}

				$state['activity'][] = sanitize_text_field((string) $message);
				if (count($state['activity']) > 12) {
					$state['activity'] = array_slice($state['activity'], -12);
				}
			}

			private function compact_products_for_job($products) {
				if (!is_array($products)) {
					return array();
				}

				$result = array();
				foreach ($products as $productData) {
					if (!is_array($productData)) {
						continue;
					}

					$result[] = $this->compact_product_for_job($productData);
				}

				return $result;
			}

			private function compact_product_for_job($productData) {
				$compact = array();
				$copyKeys = array(
					'id',
					'type',
					'sku',
					'slug',
					'name',
					'description',
					'short_description',
					'is_featured',
					'catalog_visibility',
					'stock_status',
					'is_in_stock',
					'tax_status',
					'prices',
					'categories',
					'tags',
					'images',
					'attributes',
				);

				foreach ($copyKeys as $key) {
					if (array_key_exists($key, $productData)) {
						$compact[$key] = $productData[$key];
					}
				}

				if (!empty($productData['variationDetails']) && is_array($productData['variationDetails'])) {
					$compact['variationDetails'] = array();
					foreach ($productData['variationDetails'] as $variationData) {
						if (!is_array($variationData)) {
							continue;
						}

						$compact['variationDetails'][] = $this->compact_variation_for_job($variationData);
					}
				}

				if (!empty($productData['raw']) && is_array($productData['raw'])) {
					$compactRaw = array();
					if (array_key_exists('has_options', $productData['raw'])) {
						$compactRaw['has_options'] = !empty($productData['raw']['has_options']);
					}
					if (!empty($productData['raw']['variations']) && is_array($productData['raw']['variations'])) {
						$compactRaw['variations'] = array(1);
					}
					if (!empty($compactRaw)) {
						$compact['raw'] = $compactRaw;
					}
				}

				return $compact;
			}

			private function compact_variation_for_job($variationData) {
				$compact = array();
				$copyKeys = array(
					'id',
					'sku',
					'description',
					'stock_status',
					'is_in_stock',
					'tax_status',
					'prices',
					'regular_price',
					'price',
					'sale_price',
					'attributes',
					'image',
					'images',
				);

				foreach ($copyKeys as $key) {
					if (array_key_exists($key, $variationData)) {
						$compact[$key] = $variationData[$key];
					}
				}

				if (!empty($variationData['raw']) && is_array($variationData['raw'])) {
					$compactRaw = array();
					$rawCopyKeys = array(
						'prices',
						'currency_minor_unit',
						'regular_price',
						'price',
						'sale_price',
						'stock_status',
						'is_in_stock',
						'image',
						'images',
					);
					foreach ($rawCopyKeys as $rawKey) {
						if (array_key_exists($rawKey, $variationData['raw'])) {
							$compactRaw[$rawKey] = $variationData['raw'][$rawKey];
						}
					}

					if (!empty($compactRaw)) {
						$compact['raw'] = $compactRaw;
					}
				}

				return $compact;
			}

			public function handle_import() {
			if (!current_user_can($this->required_capability())) {
				wp_die(esc_html__('You do not have permission to perform this action.', 'woo-json-metadata-importer'));
			}

			check_admin_referer(self::NONCE_ACTION);

			if (!class_exists('WooCommerce')) {
				$this->redirect_with_notice('error', 'WooCommerce is not active.');
			}

			if (
				empty($_FILES['metadata_file']) ||
				!is_array($_FILES['metadata_file']) ||
				empty($_FILES['metadata_file']['tmp_name'])
			) {
				$this->redirect_with_notice('error', 'No file was uploaded.');
			}

			$file = $_FILES['metadata_file'];
			if (!empty($file['error'])) {
				$this->redirect_with_notice('error', 'JSON file upload failed.');
			}

			$rawJson = file_get_contents($file['tmp_name']); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_get_contents_file_get_contents
			if (false === $rawJson || '' === trim($rawJson)) {
				$this->redirect_with_notice('error', 'Unable to read the uploaded file.');
			}

				$payload = json_decode($rawJson, true);
				if (JSON_ERROR_NONE !== json_last_error()) {
					$this->redirect_with_notice('error', 'Invalid JSON: ' . json_last_error_msg());
				}

			try {
				$products = $this->extract_products($payload);
			} catch (Exception $exception) {
				$this->redirect_with_notice('error', $exception->getMessage());
			}

			$summary = array(
				'created' => 0,
				'updated' => 0,
				'failed' => 0,
			);
			$errors = array();

			foreach ($products as $index => $productData) {
				try {
					$result = $this->import_product($productData);
					if ('created' === $result) {
						$summary['created']++;
					} else {
						$summary['updated']++;
					}
				} catch (Throwable $exception) {
					$summary['failed']++;
					$errors[] = sprintf('Product #%d: %s', $index + 1, $exception->getMessage());
				}
			}

			$message = sprintf(
				'Import completed. Created: %d | Updated: %d | Failed: %d',
				$summary['created'],
				$summary['updated'],
				$summary['failed']
			);

			$details = '';
			if (!empty($errors)) {
				$details = implode(' || ', array_slice($errors, 0, 5));
			}

			$status = $summary['failed'] > 0 ? 'warning' : 'success';
			$this->redirect_with_notice($status, $message, $details);
		}

		private function extract_products($payload) {
			if (is_array($payload) && isset($payload['products']) && is_array($payload['products'])) {
				return $payload['products'];
			}

			if ($this->is_list_array($payload)) {
				return $payload;
			}

			if (is_array($payload) && isset($payload['id'])) {
				return array($payload);
			}

			throw new Exception('Invalid JSON structure. Expected: { "products": [...] }.');
		}

		private function is_list_array($value) {
			if (!is_array($value)) {
				return false;
			}

			$index = 0;
			foreach ($value as $key => $_item) {
				if ($key !== $index) {
					return false;
				}
				$index++;
			}

			return true;
		}

		private function import_product($productData) {
			if (!is_array($productData)) {
				throw new Exception('Invalid product entry in JSON.');
			}

			$isVariable = $this->is_variable_product_payload($productData);
			$sku = isset($productData['sku']) ? wc_clean((string) $productData['sku']) : '';
			$productId = $sku ? (int) wc_get_product_id_by_sku($sku) : 0;
			$sourceProductId = isset($productData['id']) ? (int) $productData['id'] : 0;

			if ($productId <= 0 && $sourceProductId > 0) {
				$productId = $this->find_product_by_source_id($sourceProductId);
			}

			if ($productId <= 0 && !empty($productData['slug'])) {
				$existingBySlug = get_page_by_path(sanitize_title((string) $productData['slug']), OBJECT, 'product');
				if ($existingBySlug instanceof WP_Post) {
					$productId = (int) $existingBySlug->ID;
				}
			}

			if ($productId > 0) {
				wp_set_object_terms($productId, $isVariable ? 'variable' : 'simple', 'product_type');
			}

			if ($isVariable) {
				$product = $productId > 0 ? new WC_Product_Variable($productId) : new WC_Product_Variable();
			} else {
				$product = $productId > 0 ? new WC_Product_Simple($productId) : new WC_Product_Simple();
			}

			$isCreated = $productId <= 0;

			$this->hydrate_common_product($product, $productData);
			$this->apply_pricing($product, $productData['prices'] ?? array());
			$product->set_attributes($this->build_parent_attributes($productData, $isVariable));
			$product->set_category_ids($this->resolve_term_ids($productData['categories'] ?? array(), 'product_cat'));
			$product->set_tag_ids($this->resolve_term_ids($productData['tags'] ?? array(), 'product_tag'));
			$product->save();

			$parentId = $product->get_id();
			if ($sourceProductId > 0) {
				update_post_meta($parentId, '_wjmi_source_product_id', $sourceProductId);
			}
			$this->attach_images_to_product($parentId, $productData['images'] ?? array());

			if ($isVariable) {
				$this->import_variations($parentId, $productData);
				WC_Product_Variable::sync($parentId);
			}

			return $isCreated ? 'created' : 'updated';
		}

		private function hydrate_common_product($product, $productData) {
			$name = isset($productData['name']) ? sanitize_text_field((string) $productData['name']) : '';
			if ('' === $name) {
				$name = 'Untitled product';
			}
			$product->set_name($name);

			if (!empty($productData['slug'])) {
				$product->set_slug(sanitize_title($productData['slug']));
			}

			$product->set_description(isset($productData['description']) ? wp_kses_post((string) $productData['description']) : '');
			$product->set_short_description(isset($productData['short_description']) ? wp_kses_post((string) $productData['short_description']) : '');
			$product->set_status('publish');
			$product->set_featured(!empty($productData['is_featured']));
			$product->set_manage_stock(false);

			if (!empty($productData['sku'])) {
				$product->set_sku(wc_clean((string) $productData['sku']));
			}

			$visibility = isset($productData['catalog_visibility']) ? sanitize_key((string) $productData['catalog_visibility']) : 'visible';
			$allowedVisibility = array('visible', 'catalog', 'search', 'hidden');
			if (!in_array($visibility, $allowedVisibility, true)) {
				$visibility = 'visible';
			}
			$product->set_catalog_visibility($visibility);

			$product->set_stock_status($this->resolve_stock_status($productData));

			$taxStatus = isset($productData['tax_status']) ? sanitize_key((string) $productData['tax_status']) : 'taxable';
			$allowedTaxStatus = array('taxable', 'shipping', 'none');
			if (!in_array($taxStatus, $allowedTaxStatus, true)) {
				$taxStatus = 'taxable';
			}
			$product->set_tax_status($taxStatus);
		}

		private function apply_pricing($product, $prices) {
			if (!is_array($prices)) {
				$product->set_regular_price('');
				$product->set_sale_price('');
				return;
			}

			$minor = isset($prices['currency_minor_unit']) ? (int) $prices['currency_minor_unit'] : 2;
			$regular = $this->minor_to_decimal($prices['regular_price'] ?? ($prices['price'] ?? ''), $minor);
			$sale = $this->minor_to_decimal($prices['sale_price'] ?? '', $minor);

			$product->set_regular_price($regular);
			$product->set_sale_price($sale);
		}

		private function minor_to_decimal($value, $minorUnit) {
			if (null === $value || '' === $value) {
				return '';
			}

			$raw = str_replace(',', '.', trim((string) $value));
			if ('' === $raw || !is_numeric($raw)) {
				return '';
			}

			$minor = is_numeric($minorUnit) ? (int) $minorUnit : 2;
			$number = (float) $raw;

			if ($minor < 0) {
				$minor = 0;
			}

			// If the input already carries decimal notation, keep it as decimal.
			if (false !== strpos($raw, '.')) {
				return number_format($number, $minor, '.', '');
			}

			$decimal = $number / pow(10, $minor);
			if ($minor > 0) {
				return number_format($decimal, $minor, '.', '');
			}

			return (string) $decimal;
		}

		private function first_non_empty_price($candidates) {
			if (!is_array($candidates)) {
				return '';
			}

			foreach ($candidates as $candidate) {
				if (null === $candidate) {
					continue;
				}
				if ('' === trim((string) $candidate)) {
					continue;
				}
				return $candidate;
			}

			return '';
		}

		private function resolve_minor_unit($variationData, $parentMinor) {
			$minorCandidates = array(
				$variationData['prices']['currency_minor_unit'] ?? null,
				$variationData['currency_minor_unit'] ?? null,
				$variationData['raw']['prices']['currency_minor_unit'] ?? null,
				$variationData['raw']['currency_minor_unit'] ?? null,
				$parentMinor,
			);

			foreach ($minorCandidates as $minor) {
				if (is_numeric($minor)) {
					return (int) $minor;
				}
			}

			return 2;
		}

		private function resolve_term_ids($termItems, $taxonomy) {
			if (!is_array($termItems)) {
				return array();
			}

			$ids = array();
			foreach ($termItems as $termItem) {
				$name = '';
				$slug = '';
				if (is_array($termItem) && !empty($termItem['name'])) {
					$name = sanitize_text_field((string) $termItem['name']);
				} elseif (is_string($termItem)) {
					$name = sanitize_text_field($termItem);
				}

				if (is_array($termItem) && !empty($termItem['slug'])) {
					$slug = sanitize_title((string) $termItem['slug']);
				}

				if ('' === $name && '' !== $slug) {
					$name = str_replace('-', ' ', $slug);
				}

				if ('' === $name) {
					continue;
				}

				$term = null;
				if ('' !== $slug) {
					$existingBySlug = get_term_by('slug', $slug, $taxonomy);
					if ($existingBySlug && !is_wp_error($existingBySlug)) {
						$term = array('term_id' => (int) $existingBySlug->term_id);
					}
				}

				if (null === $term) {
					$term = term_exists($name, $taxonomy);
				}

				if (0 === $term || null === $term) {
					$args = array();
					if ('' !== $slug) {
						$args['slug'] = $slug;
					}
					$term = wp_insert_term($name, $taxonomy, $args);
				}

				if (is_wp_error($term)) {
					continue;
				}

				if (is_array($term) && isset($term['term_id'])) {
					$ids[] = (int) $term['term_id'];
				} elseif (is_numeric($term)) {
					$ids[] = (int) $term;
				}
			}

			return array_values(array_unique(array_filter($ids)));
		}

			private function build_parent_attributes($productData, $isVariable) {
				if (empty($productData['attributes']) || !is_array($productData['attributes'])) {
					return array();
				}

				$attributes = array();
				$position = 0;

				foreach ($productData['attributes'] as $rawAttribute) {
					if (!is_array($rawAttribute)) {
						continue;
					}

					$label = $this->pick_attribute_name($rawAttribute);
					if ('' === $label) {
						continue;
					}

					$slug = $this->resolve_attribute_slug($rawAttribute, $label);
					if ('' === $slug) {
						continue;
					}

					$taxonomy = wc_attribute_taxonomy_name($slug);
					$attributeId = $this->ensure_global_attribute_id($slug, $label);
					if ($attributeId <= 0 || !$this->register_missing_attribute_taxonomy($taxonomy, $label)) {
						continue;
					}

					$options = $this->extract_attribute_options($rawAttribute);
					if (empty($options)) {
						continue;
					}

					$termIds = $this->ensure_term_ids_for_taxonomy($taxonomy, $options);
					if (empty($termIds)) {
						continue;
					}

					$productAttribute = new WC_Product_Attribute();
					$productAttribute->set_id($attributeId);
					$productAttribute->set_name($taxonomy);
					$productAttribute->set_options($termIds);
					$productAttribute->set_visible(!isset($rawAttribute['visible']) || (bool) $rawAttribute['visible']);
					$productAttribute->set_variation($isVariable);
					$productAttribute->set_position($position);

					$attributes[] = $productAttribute;
					$position++;
				}

				return $attributes;
			}

			private function resolve_attribute_slug($rawAttribute, $fallbackName = '') {
				$candidates = array(
					$rawAttribute['slug'] ?? '',
					$rawAttribute['taxonomy'] ?? '',
					$rawAttribute['name'] ?? '',
					$rawAttribute['label'] ?? '',
					$fallbackName,
				);

				foreach ($candidates as $candidate) {
					$text = trim((string) $candidate);
					if ('' === $text) {
						continue;
					}

					$text = preg_replace('/^attribute_/i', '', $text);
					$text = preg_replace('/^pa_/i', '', $text);
					$slug = function_exists('wc_sanitize_taxonomy_name') ? wc_sanitize_taxonomy_name($text) : sanitize_title($text);
					if ('' !== $slug) {
						return $slug;
					}
				}

				return '';
			}

			private function ensure_global_attribute_id($slug, $label) {
				$cleanSlug = function_exists('wc_sanitize_taxonomy_name') ? wc_sanitize_taxonomy_name((string) $slug) : sanitize_title((string) $slug);
				if ('' === $cleanSlug) {
					return 0;
				}

				$attributeId = function_exists('wc_attribute_taxonomy_id_by_name') ? (int) wc_attribute_taxonomy_id_by_name($cleanSlug) : 0;
				if ($attributeId > 0) {
					return $attributeId;
				}

				if (!function_exists('wc_create_attribute')) {
					return 0;
				}

				$attributeLabel = trim((string) $label);
				if ('' === $attributeLabel) {
					$attributeLabel = ucwords(str_replace(array('-', '_'), ' ', $cleanSlug));
				}

				$created = wc_create_attribute(
					array(
						'name' => $attributeLabel,
						'slug' => $cleanSlug,
						'type' => 'select',
						'order_by' => 'menu_order',
						'has_archives' => false,
					)
				);

				if (is_wp_error($created)) {
					return function_exists('wc_attribute_taxonomy_id_by_name') ? (int) wc_attribute_taxonomy_id_by_name($cleanSlug) : 0;
				}

				delete_transient('wc_attribute_taxonomies');

				if (is_numeric($created) && (int) $created > 0) {
					return (int) $created;
				}

				return function_exists('wc_attribute_taxonomy_id_by_name') ? (int) wc_attribute_taxonomy_id_by_name($cleanSlug) : 0;
			}

			private function register_missing_attribute_taxonomy($taxonomy, $label) {
				$taxonomy = (string) $taxonomy;
				if ('' === $taxonomy) {
					return false;
				}

				if (taxonomy_exists($taxonomy)) {
					return true;
				}

				register_taxonomy(
					$taxonomy,
					apply_filters('woocommerce_taxonomy_objects_' . $taxonomy, array('product')),
					apply_filters(
						'woocommerce_taxonomy_args_' . $taxonomy,
						array(
							'hierarchical' => false,
							'show_ui' => false,
							'query_var' => true,
							'rewrite' => false,
							'public' => false,
							'show_in_nav_menus' => false,
							'show_tagcloud' => false,
							'labels' => array(
								'name' => '' !== trim((string) $label) ? trim((string) $label) : $taxonomy,
							),
							'capabilities' => array(
								'manage_terms' => 'manage_product_terms',
								'edit_terms' => 'edit_product_terms',
								'delete_terms' => 'delete_product_terms',
								'assign_terms' => 'assign_product_terms',
							),
						)
					)
				);

				return taxonomy_exists($taxonomy);
			}

			private function ensure_term_ids_for_taxonomy($taxonomy, $options) {
				if (!is_array($options) || empty($options)) {
					return array();
				}

				$ids = array();
				foreach ($options as $option) {
					$termId = $this->ensure_term_id_for_taxonomy($taxonomy, $option);
					if ($termId > 0) {
						$ids[] = $termId;
					}
				}

				return array_values(array_unique($ids));
			}

			private function ensure_term_id_for_taxonomy($taxonomy, $value) {
				$cleanValue = wc_clean((string) $value);
				$cleanValue = trim($cleanValue);
				if ('' === $cleanValue || !$this->register_missing_attribute_taxonomy($taxonomy, $taxonomy)) {
					return 0;
				}

				$term = term_exists($cleanValue, $taxonomy);
				if (is_array($term) && isset($term['term_id'])) {
					return (int) $term['term_id'];
				}
				if (is_numeric($term)) {
					return (int) $term;
				}

				$slug = sanitize_title(remove_accents($cleanValue));
				if ('' !== $slug) {
					$existingBySlug = get_term_by('slug', $slug, $taxonomy);
					if ($existingBySlug && !is_wp_error($existingBySlug)) {
						return (int) $existingBySlug->term_id;
					}
				}

				$insertArgs = '' !== $slug ? array('slug' => $slug) : array();
				$insert = wp_insert_term($cleanValue, $taxonomy, $insertArgs);
				if (is_wp_error($insert)) {
					$existingId = $insert->get_error_data('term_exists');
					if (is_numeric($existingId)) {
						return (int) $existingId;
					}

					return 0;
				}

				return is_array($insert) && isset($insert['term_id']) ? (int) $insert['term_id'] : 0;
			}

			private function resolve_term_slug_for_taxonomy($taxonomy, $value) {
				$cleanValue = wc_clean((string) $value);
				$cleanValue = trim($cleanValue);
				if ('' === $cleanValue) {
					return '';
				}

				$termId = $this->ensure_term_id_for_taxonomy($taxonomy, $cleanValue);
				if ($termId <= 0) {
					return sanitize_title(remove_accents($cleanValue));
				}

				$term = get_term($termId, $taxonomy);
				if ($term && !is_wp_error($term) && !empty($term->slug)) {
					return (string) $term->slug;
				}

				return sanitize_title(remove_accents($cleanValue));
			}

			private function normalize_attribute_candidate_key($value) {
				$text = trim(strtolower((string) $value));
				if ('' === $text) {
					return '';
				}

				$text = preg_replace('/^attribute_/', '', $text);
				$text = preg_replace('/^pa_/', '', $text);
				return sanitize_title($text);
			}

			private function pick_attribute_name($rawAttribute) {
				$candidates = array(
					$rawAttribute['name'] ?? '',
					$rawAttribute['label'] ?? '',
					$rawAttribute['slug'] ?? '',
					$rawAttribute['taxonomy'] ?? '',
				);

				foreach ($candidates as $value) {
					$text = trim((string) $value);
					if ('' === $text) {
						continue;
					}

					$text = preg_replace('/^attribute_/i', '', $text);
					$text = preg_replace('/^pa_/i', '', $text);
					$clean = wc_clean($text);
					if ('' !== $clean) {
						return $clean;
					}
				}

				return '';
			}

			private function extract_attribute_options($rawAttribute) {
				$options = array();

				if (!empty($rawAttribute['terms']) && is_array($rawAttribute['terms'])) {
					foreach ($rawAttribute['terms'] as $term) {
						if (is_array($term)) {
							if (!empty($term['name'])) {
								$options[] = wc_clean((string) $term['name']);
							} elseif (!empty($term['slug'])) {
								$options[] = wc_clean((string) $term['slug']);
							}
						} elseif (is_string($term)) {
							$options[] = wc_clean($term);
						}
					}
				}

				if (!empty($rawAttribute['options']) && is_array($rawAttribute['options'])) {
					foreach ($rawAttribute['options'] as $option) {
						if (is_string($option) || is_numeric($option)) {
							$options[] = wc_clean((string) $option);
						}
					}
				}

				if (!empty($rawAttribute['option'])) {
					$options[] = wc_clean((string) $rawAttribute['option']);
				}

				if (!empty($rawAttribute['value']) && (is_string($rawAttribute['value']) || is_numeric($rawAttribute['value']))) {
					$options[] = wc_clean((string) $rawAttribute['value']);
				}

				if (!empty($rawAttribute['values']) && is_array($rawAttribute['values'])) {
					foreach ($rawAttribute['values'] as $value) {
						if (is_string($value) || is_numeric($value)) {
							$options[] = wc_clean((string) $value);
						}
					}
				}

				$options = array_map('trim', $options);
				$options = array_filter(
					$options,
					static function ($value) {
						return '' !== $value;
					}
				);

				return array_values(array_unique($options));
			}

		private function is_variable_product_payload($productData) {
			if (!empty($productData['type']) && 'variable' === strtolower((string) $productData['type'])) {
				return true;
			}

			if (!empty($productData['variationDetails']) && is_array($productData['variationDetails'])) {
				return true;
			}

			if (!empty($productData['raw']['has_options'])) {
				return true;
			}

			if (!empty($productData['raw']['variations']) && is_array($productData['raw']['variations'])) {
				return true;
			}

			return false;
		}

		private function resolve_stock_status($payload) {
			if (is_array($payload) && !empty($payload['stock_status'])) {
				$status = sanitize_key((string) $payload['stock_status']);
				if (in_array($status, array('instock', 'outofstock', 'onbackorder'), true)) {
					return $status;
				}
			}

			if (is_array($payload) && isset($payload['is_in_stock'])) {
				return !empty($payload['is_in_stock']) ? 'instock' : 'outofstock';
			}

			return 'instock';
		}

		private function import_variations($parentId, $productData) {
			if (empty($productData['variationDetails']) || !is_array($productData['variationDetails'])) {
				return;
			}

			$parentAttributeOptions = $this->build_parent_attribute_options_map($productData['attributes'] ?? array());
			$attributeKeyMap = $this->build_attribute_key_map($productData['attributes'] ?? array());
			$parentMinor = isset($productData['prices']['currency_minor_unit']) ? (int) $productData['prices']['currency_minor_unit'] : 2;

			foreach ($productData['variationDetails'] as $variationData) {
				if (!is_array($variationData)) {
					continue;
				}

				$variationSku = !empty($variationData['sku']) ? wc_clean((string) $variationData['sku']) : '';
				$sourceVariationId = isset($variationData['id']) ? (int) $variationData['id'] : 0;
				$variationId = 0;

				if ($variationSku) {
					$existingId = (int) wc_get_product_id_by_sku($variationSku);
					if ($existingId > 0) {
							$postType = get_post_type($existingId);
							$existingParent = (int) wp_get_post_parent_id($existingId);
							if ('product_variation' !== $postType || ($existingParent > 0 && $existingParent !== (int) $parentId)) {
								throw new Exception(sprintf('Variation SKU conflict: %s', $variationSku));
							}
						$variationId = $existingId;
					}
				}

				if ($variationId <= 0 && $sourceVariationId > 0) {
					$variationId = $this->find_variation_by_source_id($parentId, $sourceVariationId);
				}

				$variation = $variationId > 0 ? new WC_Product_Variation($variationId) : new WC_Product_Variation();
				$variation->set_parent_id($parentId);
				$variation->set_status('publish');

				if ($variationSku) {
					$variation->set_sku($variationSku);
				}

				$variation->set_description(isset($variationData['description']) ? wp_kses_post((string) $variationData['description']) : '');
				$variation->set_manage_stock(false);
				$variation->set_stock_status($this->resolve_stock_status($variationData));

				$taxStatus = isset($variationData['tax_status']) ? sanitize_key((string) $variationData['tax_status']) : '';
				if (!in_array($taxStatus, array('taxable', 'shipping', 'none'), true)) {
					$taxStatus = 'taxable';
				}
				$variation->set_tax_status($taxStatus);

				$minor = $this->resolve_minor_unit($variationData, $parentMinor);
				$rawRegular = $this->first_non_empty_price(
					array(
						$variationData['prices']['regular_price'] ?? null,
						$variationData['prices']['price'] ?? null,
						$variationData['regular_price'] ?? null,
						$variationData['price'] ?? null,
						$variationData['raw']['prices']['regular_price'] ?? null,
						$variationData['raw']['prices']['price'] ?? null,
						$variationData['raw']['regular_price'] ?? null,
						$variationData['raw']['price'] ?? null
					)
				);
				$rawSale = $this->first_non_empty_price(
					array(
						$variationData['prices']['sale_price'] ?? null,
						$variationData['sale_price'] ?? null,
						$variationData['raw']['prices']['sale_price'] ?? null,
						$variationData['raw']['sale_price'] ?? null
					)
				);
				$variationRegular = $this->minor_to_decimal($rawRegular, $minor);
				$variationSale = $this->minor_to_decimal($rawSale, $minor);
				$variation->set_regular_price($variationRegular);
				$variation->set_sale_price($variationSale);

				$variationAttrs = $this->extract_variation_attributes(
					$variationData['attributes'] ?? array(),
					$attributeKeyMap,
					$parentAttributeOptions
				);
				if (!empty($variationAttrs)) {
					$variation->set_attributes($variationAttrs);
				}

				$variation->save();
				if ($sourceVariationId > 0) {
					update_post_meta($variation->get_id(), '_wjmi_source_variation_id', $sourceVariationId);
				}

				$variationImageUrl = $this->resolve_variation_image_url($variationData);
				if ('' !== $variationImageUrl) {
					$imageId = $this->sideload_image_attachment($variationImageUrl, $variation->get_id());
					if ($imageId > 0) {
						$variation->set_image_id($imageId);
						$variation->save();
					}
				}
			}
		}

			private function build_attribute_key_map($attributes) {
				$map = array();
				if (!is_array($attributes)) {
					return $map;
				}

				foreach ($attributes as $attribute) {
					if (!is_array($attribute)) {
						continue;
					}

					$name = $this->pick_attribute_name($attribute);
					$slug = $this->resolve_attribute_slug($attribute, $name);
					if ('' === $slug) {
						continue;
					}

					$taxonomy = wc_attribute_taxonomy_name($slug);
					$canonicalKey = sanitize_title($slug);
					$map[$canonicalKey] = $taxonomy;
					$map[$this->normalize_attribute_candidate_key($taxonomy)] = $taxonomy;

					$candidates = array(
						$attribute['name'] ?? '',
						$attribute['label'] ?? '',
						$attribute['slug'] ?? '',
						$attribute['taxonomy'] ?? '',
						$taxonomy,
					);

					foreach ($candidates as $candidate) {
						$candidateKey = $this->normalize_attribute_candidate_key($candidate);
						if ('' !== $candidateKey) {
							$map[$candidateKey] = $taxonomy;
						}
					}
				}

				return $map;
			}

			private function build_parent_attribute_options_map($attributes) {
				$map = array();
				if (!is_array($attributes)) {
					return $map;
				}

			foreach ($attributes as $attribute) {
				if (!is_array($attribute)) {
					continue;
				}

					$name = $this->pick_attribute_name($attribute);
					$slug = $this->resolve_attribute_slug($attribute, $name);
					if ('' === $slug) {
						continue;
					}

					$key = wc_attribute_taxonomy_name($slug);
					$options = $this->extract_attribute_options($attribute);
					if (!empty($options)) {
						$termIds = $this->ensure_term_ids_for_taxonomy($key, $options);
						$termNames = array();
						foreach ($termIds as $termId) {
							$term = get_term((int) $termId, $key);
							if ($term && !is_wp_error($term) && !empty($term->name)) {
								$termNames[] = wc_clean((string) $term->name);
							}
						}

						$map[$key] = !empty($termNames) ? array_values(array_unique($termNames)) : $options;
					}
				}

				return $map;
			}

			private function extract_variation_attributes($attributes, $attributeKeyMap, $parentAttributeOptions) {
				$result = array();

			if (!is_array($attributes)) {
				return $result;
			}

			$fallbackParentKeys = array_keys($parentAttributeOptions);
			$fallbackIndex = 0;

				foreach ($attributes as $attribute) {
					if (!is_array($attribute)) {
						$fallbackIndex++;
						continue;
					}

					$rawCandidates = array(
						$attribute['name'] ?? '',
						$attribute['label'] ?? '',
						$attribute['slug'] ?? '',
						$attribute['taxonomy'] ?? '',
						$attribute['key'] ?? '',
						$attribute['attribute'] ?? '',
					);

					$key = '';
					foreach ($rawCandidates as $candidate) {
						$candidateKey = $this->normalize_attribute_candidate_key($candidate);
						if ('' !== $candidateKey && isset($attributeKeyMap[$candidateKey])) {
							$key = $attributeKeyMap[$candidateKey];
							break;
						}
					}

				if ('' === $key && isset($fallbackParentKeys[$fallbackIndex])) {
					$key = $fallbackParentKeys[$fallbackIndex];
				}

				if ('' === $key) {
					$fallbackIndex++;
					continue;
				}

					$options = $this->extract_attribute_options($attribute);
					$value = !empty($options) ? (string) $options[0] : '';
					if ('' !== $value) {
						$matchedValue = $this->match_value_to_parent_options($value, $parentAttributeOptions[$key] ?? array());
						$slugValue = $this->resolve_term_slug_for_taxonomy($key, $matchedValue);
						if ('' !== $slugValue) {
							$result[$key] = $slugValue;
						}
					}

				$fallbackIndex++;
			}

			return $result;
		}

		private function match_value_to_parent_options($value, $parentOptions) {
			$cleanValue = wc_clean((string) $value);
			if ('' === $cleanValue || !is_array($parentOptions) || empty($parentOptions)) {
				return $cleanValue;
			}

			$needle = $this->normalize_attribute_match($cleanValue);
			foreach ($parentOptions as $parentOption) {
				$candidate = wc_clean((string) $parentOption);
				if ($this->normalize_attribute_match($candidate) === $needle) {
					return $candidate;
				}
			}

			foreach ($parentOptions as $parentOption) {
				$candidate = wc_clean((string) $parentOption);
				$normalizedCandidate = $this->normalize_attribute_match($candidate);
				if ('' !== $needle && (false !== strpos($normalizedCandidate, $needle) || false !== strpos($needle, $normalizedCandidate))) {
					return $candidate;
				}
			}

			return $cleanValue;
		}

		private function normalize_attribute_match($value) {
			return sanitize_title(remove_accents((string) $value));
		}

		private function resolve_variation_image_url($variationData) {
			if (!is_array($variationData)) {
				return '';
			}

			$candidates = array();

			if (!empty($variationData['image'])) {
				$candidates = array_merge($candidates, $this->extract_image_candidates($variationData['image']));
			}
			if (!empty($variationData['images'])) {
				$candidates = array_merge($candidates, $this->extract_image_candidates($variationData['images']));
			}

			if (!empty($variationData['raw']) && is_array($variationData['raw'])) {
				if (!empty($variationData['raw']['image'])) {
					$candidates = array_merge($candidates, $this->extract_image_candidates($variationData['raw']['image']));
				}
				if (!empty($variationData['raw']['images'])) {
					$candidates = array_merge($candidates, $this->extract_image_candidates($variationData['raw']['images']));
				}
			}

			foreach ($candidates as $candidate) {
				$url = esc_url_raw((string) $candidate);
				if ('' !== $url) {
					return $url;
				}
			}

			return '';
		}

		private function extract_image_candidates($imageData) {
			$urls = array();

			if (is_string($imageData)) {
				$urls[] = $imageData;
				return $urls;
			}

			if (!is_array($imageData)) {
				return $urls;
			}

			$isList = array_keys($imageData) === range(0, count($imageData) - 1);
			if ($isList) {
				foreach ($imageData as $item) {
					$urls = array_merge($urls, $this->extract_image_candidates($item));
				}
				return $urls;
			}

			$keys = array('src', 'thumbnail', 'url', 'full', 'original', 'srcset');
			foreach ($keys as $key) {
				if (!empty($imageData[$key]) && is_string($imageData[$key])) {
					$urls[] = $imageData[$key];
				}
			}

			return $urls;
		}

		private function attach_images_to_product($productId, $images) {
			if (!is_array($images) || empty($images)) {
				return;
			}

			$ids = array();
			foreach ($images as $image) {
				$url = '';
				if (is_array($image) && !empty($image['src'])) {
					$url = esc_url_raw((string) $image['src']);
				} elseif (is_string($image)) {
					$url = esc_url_raw($image);
				}

				if ('' === $url) {
					continue;
				}

				$attachmentId = $this->sideload_image_attachment($url, $productId);
				if ($attachmentId > 0) {
					$ids[] = $attachmentId;
				}
			}

			if (empty($ids)) {
				return;
			}

			$ids = array_values(array_unique($ids));
			$product = wc_get_product($productId);
			if (!$product) {
				return;
			}

			$product->set_image_id($ids[0]);
			$product->set_gallery_image_ids(array_slice($ids, 1));
			$product->save();
		}

		private function sideload_image_attachment($url, $parentId) {
			$existingId = $this->find_attachment_by_source_url($url);
			if ($existingId > 0) {
				return $existingId;
			}

			require_once ABSPATH . 'wp-admin/includes/file.php';
			require_once ABSPATH . 'wp-admin/includes/media.php';
			require_once ABSPATH . 'wp-admin/includes/image.php';

			$attachmentId = media_sideload_image($url, $parentId, null, 'id');
			if (is_wp_error($attachmentId)) {
				return 0;
			}

			update_post_meta((int) $attachmentId, '_wjmi_source_url', esc_url_raw($url));
			return (int) $attachmentId;
		}

		private function find_attachment_by_source_url($url) {
			$ids = get_posts(
				array(
					'post_type' => 'attachment',
					'post_status' => 'inherit',
					'numberposts' => 1,
					'fields' => 'ids',
					'meta_key' => '_wjmi_source_url',
					'meta_value' => esc_url_raw($url),
				)
			);

			if (!empty($ids)) {
				return (int) $ids[0];
			}

			return 0;
		}

		private function find_product_by_source_id($sourceProductId) {
			$ids = get_posts(
				array(
					'post_type' => 'product',
					'post_status' => array('publish', 'draft', 'pending', 'private'),
					'numberposts' => 1,
					'fields' => 'ids',
					'meta_key' => '_wjmi_source_product_id',
					'meta_value' => (string) $sourceProductId,
				)
			);

			if (!empty($ids)) {
				return (int) $ids[0];
			}

			return 0;
		}

		private function find_variation_by_source_id($parentId, $sourceVariationId) {
			$ids = get_posts(
				array(
					'post_type' => 'product_variation',
					'post_parent' => (int) $parentId,
					'post_status' => array('publish', 'private'),
					'numberposts' => 1,
					'fields' => 'ids',
					'meta_key' => '_wjmi_source_variation_id',
					'meta_value' => (string) $sourceVariationId,
				)
			);

			if (!empty($ids)) {
				return (int) $ids[0];
			}

			return 0;
		}

		private function redirect_with_notice($status, $message, $details = '') {
			$args = array(
				'page' => self::MENU_SLUG,
				'wjmi_status' => sanitize_key($status),
				'wjmi_message' => sanitize_text_field((string) $message),
			);

			if ('' !== $details) {
				$args['wjmi_details'] = sanitize_text_field((string) $details);
			}

			$url = add_query_arg($args, admin_url('admin.php'));
			wp_safe_redirect($url);
			exit;
		}
	}
}

add_action(
	'plugins_loaded',
	static function () {
		new WJMI_Plugin();
	}
);
